### ISSUE TITLE
npm run setup fails

### ISSUE THREAD

**Issue by palerdot** [mxstbr/react-boilerplate#1052] opened 2016-09-28 16:39 UTC
`npm run setup` fails after cloning the repo

OS: Ubuntu 14.04
node: 4.4.7
npm: 2.15.8

The following error is thrown
`          Cannot find module 'lodash/defaultsDeep'`

**Comment by chaintng** [comment] 2016-09-28 17:00
i test on latest commit on dev branch and it work correctly.

**Comment by amilajack** [comment] 2016-09-28 17:02
@palerdot **Use latest npm/node versions**

```
npm cache clean
rm -rf node_modules
npm i -@ npm@latest
npm i
```

**Comment by palerdot** [comment] 2016-09-28 17:04
I cannot update npm from 4.x to 6.x because of some local dev reasons. Is there any way to make it work on node 4.x version?

**Comment by chaintng** [comment] 2016-09-28 17:06
@palerdot do you see `node_modules/lodash/defaultsDeep` files in your project directory ?
If not, please show me `node_modules/lodash/package.json` file

**Comment by palerdot** [comment] 2016-09-28 18:04
@chaintng I do not see lodash package installed at all. The script errors out before installing it. I'm seeing only `chalk` and `shelljs` installed.

**Comment by ayoungh** [comment] 2016-09-28 18:54
I am having the same issue, mac, node -v 4.1.2 do I have to update to node v6?

**Comment by ayoungh** [comment] 2016-09-28 18:58
Even using nvm, on version 6 node I am getting an error running setup:

` node ./internals/scripts/setup.js

module.js:457
`

**Comment by amilajack** [comment] 2016-09-28 19:03
Try following https://github.com/mxstbr/react-boilerplate/issues/1052#issuecomment-250230241

**Comment by amilajack** [comment] 2016-09-30 19:44
@ayoungh did this work for you?

**Comment by palerdot** [comment] 2016-09-30 20:20
I updated npm to latest and kept node at 4.x and it worked for me.

**Comment by amilajack** [comment] 2016-09-30 21:49
Glad to hear that! Closing this because you resolved this. @mxstbr should we add in the readme that `npm@2` is not supported?

**Closed by amilajack** 2016-09-30 21:49 UTC
Labels: installation-failuire

**Comment by mxstbr** [comment] 2016-10-01 00:35
> should we add in the readme that npm@2 is not supported?

Yes good point, we should mention that somewhere!

**Comment by gihrig** [comment] 2016-10-01 00:38
How about in [QuickStart](https://github.com/mxstbr/react-boilerplate#quick-start)?

That's where first time users (should) be looking. Also mention the requirement of Node 4+

**Comment by sedubois** [comment] 2016-10-01 06:30
It's already documented: https://github.com/mxstbr/react-boilerplate/blob/master/package.json#L10

**Comment by gihrig** [comment] 2016-10-01 06:54
@sedubois That's configuration, not documentation. 

The problem is not that the information is really so obscure, it's that the information is not in a place where new users are likely to look.

Also, now that you point that out, node >= 4.6.0 (current LTS) should be listed in package.json as well.

**Comment by sedubois** [comment] 2016-10-01 06:59
Yes, `package.json` should mention node as well.

But IMHO, the code should serve as documentation as much as possible, because DRY. A middle ground could be to reference that package.json section from the README (so that the version is only written once and therefore doc won't become incoherent later on when package.json changes).

**Comment by gihrig** [comment] 2016-10-01 19:51
I agree, DRY is an issue to be sure. We have similar issues in other places. It would be really nice if package.json could be made the single source of truth for all of these:

[npmcheckversion.js#L6](https://github.com/mxstbr/react-boilerplate/blob/3816242347c732b81686961d4faf6f7776ae309a/internals/scripts/npmcheckversion.js#L6)
[config.js#L7](https://github.com/mxstbr/react-boilerplate/blob/8693af3708e31f25fc0883256da605b3ccc03c9a/internals/config.js#L7)

**Comment by tomers** [comment] 2016-10-09 09:01
I happened to have npm<3 and I just checked out latest revision (Ubuntu 16.04 x64). I did not get a proper error message ([ERROR: React Boilerplate] You need npm version @>=3), as suggested by https://github.com/mxstbr/react-boilerplate/blob/3816242347c732b81686961d4faf6f7776ae309a/internals/scripts/npmcheckversion.js#L6. Instead, I got the following cryptic error message:

```
$ git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git && cd react-boilerplate/        Cloning into 'react-boilerplate'...
remote: Counting objects: 286, done.
remote: Compressing objects: 100% (247/247), done.
remote: Total 286 (delta 28), reused 183 (delta 13), pack-reused 0
Receiving objects: 100% (286/286), 1.72 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (28/28), done.
Checking connectivity... done.
tomer@Kubuntu:~/dev/react-boilerplate$ npm run setup

> react-boilerplate@3.2.1 presetup /home/tomer/dev/react-boilerplate
> npm i chalk shelljs

chalk@1.1.3 node_modules/chalk
├── escape-string-regexp@1.0.5
├── supports-color@2.0.0
├── ansi-styles@2.2.1
├── has-ansi@2.0.0 (ansi-regex@2.0.0)
└── strip-ansi@3.0.1 (ansi-regex@2.0.0)

shelljs@0.7.4 node_modules/shelljs
├── interpret@1.0.1
├── rechoir@0.6.2 (resolve@1.1.7)
└── glob@7.1.1 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.5, minimatch@3.0.3)

> react-boilerplate@3.2.1 setup /home/tomer/dev/react-boilerplate
> node ./internals/scripts/setup.js


Cleaning old repository ✓
Installing dependencies. ✓ (This might take a while)Installing dependencies
Initialising new repository ✓
Done!
> react-boilerplate@3.2.1 postsetup /home/tomer/dev/react-boilerplate
> npm run build:dll


> react-boilerplate@3.2.1 build:dll /home/tomer/dev/react-boilerplate
> node ./internals/scripts/dependencies.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/tomer/dev/react-boilerplate/internals/scripts/dependencies.js:15:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:dll"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.2.1 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.2.1 build:dll script 'node ./internals/scripts/dependencies.js'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/dependencies.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tomer/dev/react-boilerplate/npm-debug.log

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "setup"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.2.1 postsetup: `npm run build:dll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.2.1 postsetup script 'npm run build:dll'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:dll
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tomer/dev/react-boilerplate/npm-debug.log
```

**Comment by VladislavSournine** [comment] 2016-10-13 12:03
;-(

`module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/guitar/react/experiment/internals/scripts/setup.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.2.1 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.2.1 setup script 'node ./internals/scripts/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.
`

**Comment by gihrig** [comment] 2016-10-14 03:37
@VladislavSournine 

> Error: Cannot find module '/Users/guitar/react/experiment/internals/scripts/setup.js'

Setup is a self-deleting file. Since you have run it once it's now gone. But no problem, just run `npm install`.

**Comment by setzer777** [comment] 2016-10-14 03:40
Here's my solution overall:
With the fear of having a mess with my npm and node versions (cuz I'm using nvm and i didn't want to get some version conflicts), what I did at the end was
```sh
npm install npm # This will install the latest version of npm only in the folder
npm cache clean
npm install
```

Everything just started working :)
@tomers @VladislavSournine

**Comment by kubek80** [comment] 2016-11-12 12:33
Installation failed for me on node v5.12.0 (npm v3.8.6).
(before I opened package.json I had two tries with 4.6)
No problems with latest version (6.9.1 - with and without Yarn).
Since I didn't use Yarn before (I wish I new about it during my last project!) it took be around 30mins to check all scenarios.

Information about supported node version in quick start section of readme would definitely improve first impression (also would prevent people forced to use certain version of node from trying and raising issues). After all it is a quick start :)

P.S. great work, thanks!
