### ISSUE TITLE
Error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zweicoder** [mxstbr/react-boilerplate#465] opened 2016-06-04 06:28 UTC
I'm getting this error when running `npm start` on a newly cleaned app. I suspect it is due to not properly configuring `nginx` but I'm not sure and am not using `nginx` to host it. If so is there a way to disable it?
```
Error: panic: runtime error: invalid memory address or nil pointer dereference

github.com/inconshreveable/olive/recover.go:40
runtime/asm_amd64.s:403
reflect/value.go:419
reflect/value.go:296
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
<autogenerated>:132
github.com/inconshreveable/olive/recover.go:29
runtime/asm_amd64.s:401
runtime/panic.go:387
github.com/inconshreveable/olive/error.go:37
runtime/asm_amd64.s:401
runtime/panic.go:387
runtime/panic.go:42
runtime/sigpanic_unix.go:26
lib/tunnel/client/reconnecting.go:42
lib/tunnel/client/session.go:97
ngrok/tunnel_session.go:129
ngrok/web_api.go:95
runtime/asm_amd64.s:403
reflect/value.go:419
reflect/value.go:296
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/error.go:41
runtime/asm_amd64.s:403
reflect/value.go:419
reflect/value.go:296
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/recover.go:32
runtime/asm_amd64.s:403
reflect/value.go:419
reflect/value.go:296
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/logger.go:17
runtime/asm_amd64.s:403
reflect/value.go:419
reflect/value.go:296
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:250
github.com/go-martini/martini/router.go:120
ngrok/src/ngrok/web.go:25
runtime/asm_amd64.s:403
reflect/value.go:419
reflect/value.go:296
github.com/codegangsta/inject/inject.go:102
github.com/go-martini/martini/martini.go:173
github.com/go-martini/martini/martini.go:69
```

**Comment by mxstbr** [comment] 2016-06-04 11:40
We don't use nginx at all, we have an express.js server running in the background.

Due to this highly likely being a problem with your local setup and nothing we can fix from our side, I'll close this issue for now! Feel free to continue the discussion though.

**Closed by mxstbr** 2016-06-04 11:40 UTC

**Comment by zweicoder** [comment] 2016-06-05 13:25
hmm it's a newly initialized and cleaned app though. I really only ran `npm run setup` and then `npm run clean`. Any setup problems I should look out for?

**Comment by mxstbr** [comment] 2016-06-05 17:09
Hm, we fixed one yesterday so maybe try cloning and setting up again?

**Comment by Globolobo** [comment] 2016-07-18 19:52
I'm only using an express server and i'm running into the same issue.

**Comment by gihrig** [comment] 2016-07-18 20:07
@Globolobo Please describe the command sequence you are using to reproduce the error.

Do you see all the `.go` files as in the OP? These are not part or react-boilerplate, could this be a GitHub error not related to react-boilerplate?

I run:
`git clone ...`
`cd react-boilerplate`
`npm start` (get example app on localhost)
`npm clean`
`npm start` (get "This is the Homepage" on localhost)

**Comment by Globolobo** [comment] 2016-07-18 20:36
@gihrig thanks for the quick response! As I mentioned before it's an ngrok issue, they're aware of it but haven't tackled it yet (which is a dependency for boilerplate) 

As far as seeing the same errors as OP, yea, i'm seeing the exact same ones. 

I'm running an older version of boilerplate that had ngrok running by default on the server. So in order to reproduce the issue with the current boilerplate version, you need to set the "ENABLE_TUNNEL" enviro variable to true.

the steps i did are: 
```
git clone ...
cd react-boilerplate
npm install
export ENABLE_TUNNEL="true"
npm start 
```
So this issue ONLY affects people that need to enable the tunnel, or people that were using the previous version of the boilerplate when ngrok was default.

**Comment by gihrig** [comment] 2016-07-18 20:59
@Globolobo Thanks for the clarification!

FWIW, `npm run start:tunnel` and `export ENABLE_TUNNEL="true"` both work as expected with the current react-boilerplate.

Thanks for your contribution 😃
