### ISSUE TITLE
No server-side rendering ?

### ISSUE THREAD

**Issue by sap9433** [mxstbr/react-boilerplate#522] opened 2016-06-11 02:34 UTC
We will like to have a server side rendering functionality with this starter.

**Comment by wdjungst** [comment] 2016-06-11 02:40
Duplicate issue

**Comment by sap9433** [comment] 2016-06-11 02:45
couldn't find the duplicate , please refer the issue number I'll close this.

**Comment by wdjungst** [comment] 2016-06-11 03:12
Maybe not exact dup but discussed here https://github.com/mxstbr/react-boilerplate/issues/174

**Comment by mxstbr** [comment] 2016-06-11 07:31
Yeah, duplicate of #174, please discuss there!

**Closed by mxstbr** 2016-06-11 07:31 UTC

**Comment by mxstbr** [comment] 2016-06-11 10:34
@sap9433 you might want to join us on Gitter for discussions: https://gitter.im/mxstbr/react-boilerplate :+1:
