### ISSUE TITLE
page does not render in IE11

### ISSUE THREAD

**Issue by ygist** [mxstbr/react-boilerplate#800] opened 2016-07-30 01:19 UTC
My project doesn't render anymore in IE11. http://reactboilerplate.com/ seems to have the same issue. After loading, the webpage is completely blank and there are no errors in the console.

I've tried using babel-preset-es2015-ie but it didn't help.

Any help or suggestions would be appreciated.

**Comment by chaintan17** [comment] 2016-07-31 03:11
I have a problem with this on Safari also. It just stop working on production. I guess it is about dependencies after it got update.
Btw, i got some error show in my console ststing uncaught promise

**Comment by gihrig** [comment] 2016-07-31 03:15
@chaintan17 Can you give us more info on the steps to reproduce?

I just pushed a dependency update #803 and I had no problems in Safari.

**Comment by chaintan17** [comment] 2016-07-31 08:41
![image](https://cloud.githubusercontent.com/assets/2979072/17275504/1682c12c-5735-11e6-8c35-cd5ec1bedd72.png)

I spend my whole sunday fixing this bug on Safari :(...
Look like because i install `dotenv` library and in produciton server, there is no `.env` file (because it actaully set in ENVIRONMENT variables)
and it annoy Safari ...

So, the problem is not related to the code. I'm not sure about what IE11 problem then.

**Comment by chaintan17** [comment] 2016-07-31 09:21
No... it's not about `dotenv`

It still happen occasionally. After hit refresh many times, few of the request got blank response with below error in console.log

I will try reproduce it if it occurs in sample boilerplate.
![image](https://cloud.githubusercontent.com/assets/2979072/17275689/bd4dee64-573a-11e6-8711-fb6e630bd8df.png)

**Comment by IljaDaderko** [comment] 2016-08-05 08:29
+1 I still see issues when testing http://reactboilerplate.com in ie10, ie11 and refference to #805 didn't really clear up the path I need to take for a fix. @chaintan17 did you manage to overcome it?

**Comment by mxstbr** [comment] 2016-08-11 12:37
This should be fixed in the newest verison of the boilerplate if #805 was indeed the problem. Can you verify @chaintan17?

**Comment by seb0zz** [comment] 2016-08-26 11:15
For me it only worked when removing `"transform-react-inline-elements"` from package.json

**Comment by mxstbr** [comment] 2016-09-18 12:45
Closing due to inactivity, let me know if you're still running into this!

**Closed by mxstbr** 2016-09-18 12:45 UTC
Labels: bug

**Comment by SeunghunSunmoonLee** [comment] 2018-03-26 13:45
Does this issue still exist? One of my client recently reported the same problem on IE 11 on my reaact-boierplate, firebase, antd design codebase
