### ISSUE TITLE
Hot reloading for CSS is broken

### ISSUE THREAD

**Issue by christianvuerings** [mxstbr/react-boilerplate#476] opened 2016-06-05 23:14 UTC
**To Reproduce**
- Start the server with `npm run start`
- Make a change in `app/containers/App/styles.css`

**Result**
Page looks broken and the previous styles on the element are removed. We can fix this by manually reloading the page.

**Comment by mxstbr** [comment] 2016-06-06 08:44
Dang, that shouldn't be happening! Are you running the example app, and any ideas what could be the root of the problem?

**Comment by joehua87** [comment] 2016-06-06 08:46
@mxstbr I faced this too & thought it was caused by pure function

**Comment by joehua87** [comment] 2016-06-06 08:52
I've tried & it's worked after converting to ES6 class

**Comment by tsm91** [comment] 2016-06-06 09:42
@joehua87 yeah, its a v1 caveat, https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#the-following-modules-couldnt-be-hot-updated-they-would-need-a-full-reload

yet another reason to upgrade to RHL v3 beta

**Comment by mxstbr** [comment] 2016-06-06 17:51
Ah, thanks for trying that out @joehua87! Closing since this is nothing we can change at the moment!

**Closed by mxstbr** 2016-06-06 17:51 UTC
Labels: bug
