### ISSUE TITLE
Props not rendering unless container set as route.

### ISSUE THREAD

**Issue by RyanFDev** [mxstbr/react-boilerplate#982] opened 2016-09-12 05:16 UTC
I have a strange issue with a NavBar container I am attempting to make.

Currently I have a NavBar container with a NavLink component that currently just passes along the props to the Button component you wrote for the example app.

```
function NavLink(props) {
    return (
      <div className={styles.navLink}>
        <Button {...props}/>
      </div>
    );
  }
```

I have the NavBar in my App container and it is a smart container yet when I click a link using handleRoute I get an error _this.props.changeRoute is note a function.

However I have it mapped to dispatch in my NavBar container 

```
function mapDispatchToProps(dispatch) {
  return {
    changeRoute: (url) => dispatch(push(url)),

    dispatch,
  };
}
```

Now to make sure I wasn't doing something wrong I copied your FeaturesPage from master and created a route to it.

In this scenario the link works. However if I place <FeaturesPage/> in the App or HomePage container I get the same exact error I get with my NavBar.

When I check the props the nested components have none (other than the two get functions) where as when used as a route they have all the expected props.

I feel like I'm overlooking something. Why are the links working when the container is the main route but not when I have it nested in a routed container?

Does connect only work on a route? If so what is the best approach to creating a NavBar with logic?

Sidenote: When using the route generator it works for components only not containers.

**Comment by Anthelmed** [comment] 2016-09-21 16:19
Try this :
export default connect(null, mapDispatchToProps)(NavBar);

**Comment by amilajack** [comment] 2016-09-23 04:35
@RyanFDev did this end up working out for you?

**Comment by RyanFDev** [comment] 2016-09-24 15:49
Sorry haven't had a chance to work on this project last few days. Unfortunately this fix did not work, I was already using that export. 

It appears as though the container just will not receive any props when in the App container. I'm going to spend today checking it out and once I see what I am doing wrong I'll be sure to update this thread.

**Comment by bladepop** [comment] 2016-11-25 11:28
Hi,
I have encountered a similar problem, I found that the cause was a wrong way to import the container,
I imported it without the connect like this:
`import { Container } from '../Container`
When I swapped this line to
`import Container from '..Container`
the connect was called and props were applied,
however you should make sure that your mapStateToProps function can access the store,
Because the container you are using is not a generated route, it will not have its reducers automatically loaded and therefore when the generated selectors are called, the store doesn't have your container initial state.
Hope this helps :)

**Comment by mxstbr** [comment] 2016-12-08 12:39
Since there was no reply to @bladepop's solution I'll close this!

**Closed by mxstbr** 2016-12-08 12:39 UTC
Labels: waiting-for-response
