### ISSUE TITLE
Add an async props connect

### ISSUE THREAD

**Issue by utkuturunc** [mxstbr/react-boilerplate#820] opened 2016-08-03 08:03 UTC
It is usually desirable to defer the rendering of a component until all props are loaded.

A project that does this is:
https://github.com/makeomatic/redux-connect

And redux-saga implementation can be done as explained in:
https://github.com/yelouafi/redux-saga/issues/161

**Comment by IljaDaderko** [comment] 2016-08-03 12:54
@utkuturunc I believe this is handled in via sagas

**Comment by gihrig** [comment] 2016-08-03 16:48
@utkuturunc Did you have a reproducible error/problem caused by render before props are available?

**Comment by utkuturunc** [comment] 2016-08-03 20:43
@gihrig I prefer to ensure all props are loaded and ready before the first render. I believe it is a better practice.

@IljaDaderko How do I enable this for my custom sagas and containers?

**Comment by mxstbr** [comment] 2016-08-04 05:21
We don't do server-side rendering, which redux async connect is used for as far as I can tell. Not sure what the usecase would be for us so I'll close this for now!

**Closed by mxstbr** 2016-08-04 05:21 UTC

**Comment by utkuturunc** [comment] 2016-08-04 08:40
We don't have to implement the server-side functionalities.

It ensures all props are loaded before the route is loaded. It prevents errors like "undefined is not a function", "Cannot read property of undefined" etc.

And it saves the trouble of writing if !loaded return <Loading> else return ... to every component that needs async data on load.

As far as I know, this approach is also used by Facebook in Relay as well as several other boilerplates.

https://github.com/ericclemmons/react-resolver
https://github.com/andreypopp/react-async
https://github.com/rackt/async-props

**Comment by mxstbr** [comment] 2016-08-04 08:46
I've honest to god never seen this error, I don't know what would introduce it? Why would the props not be there?

**Comment by utkuturunc** [comment] 2016-08-04 08:59
Let's say you have a route for displaying a user's profile. And in that route you have something similar to

`<span>{ this.props.user.name.first }></span>`

In the componentWillMount hook you can call something like this.props.getProfile() which will be caught by a saga and then the store will be populated with the profile data. Until this is done the rendered value is dependent on your initial state.

If your initial state was

`{ user: {} }`

then on the first render you are going to get an error saying "cannot read the property 'first' of undefined" (since user.name is undefined).

Possible solutions are
1- Use a loading component

`if (this.props.loading) { return <span>Please Wait</span> } else { return <span>{ this.props.user.name.first }></span> }`

Adding similar logic to every component becomes tedious.

2- Use a more detailed initial state.

`{ user: { name: { first: '' } } }`

This will prevent the error but the component will be rendered without a text. When the loading is finally complete the layout of the page will change (due to loaded content).

Also we don't always know the form of the prop so we cannot always write a complete initial state.

3- Use a props resolver library

All being said these libraries also synchronize the loading of several async requests (using Promise.all) so that all of the data in the page shows up at the same time. Otherwise everything pops up when they are ready, the page loads in several steps and the layout changes several times.

**Comment by mxstbr** [comment] 2016-08-04 10:24
Right, but then you still to implement a loading indicator, right? Otherwise the user will have an empty page until the data loads which isn't really a better use experience?

**Comment by utkuturunc** [comment] 2016-08-04 10:42
User sees the previous content until the props are ready so no empty pages.

Of course that makes it like the app is unresponsive. A nicely placed loading indicator solves this issue. With this approach the whole app only needs a single loading indicator (more can be used, of course). This brings the problem of the state management of the global loading indicator.

A few trick that could be used are:
- Creating a http interceptor (activate the spinner at the beginning of the request and deactivate when the response is ready). Not all async actions are http requests so this is not a general solution.
- Creating a global reducer that acts on action types that have _START, _SUCCESS, _ERROR in somewhere. This approach is very simple however it is an opinionated way.
- Creating higher order sagas that control the loading state.
