### ISSUE TITLE
Issue in IE10

### ISSUE THREAD

**Issue by RukmaniD** [mxstbr/react-boilerplate#202] opened 2016-02-29 07:59 UTC
This example is not working ie10.screen is not getting rendered.

**Comment by mxstbr** [comment] 2016-02-29 08:08
Are you on the `master` branch or on the `v3.0.0` branch? 

I have not cross-browser tested the example at all, so it's possible that this is a bug — do you have any idea what happens?

**Comment by RukmaniD** [comment] 2016-02-29 08:36
I have cloned it to my local and then tried running it, through npm start.It is rendering fine in mozilla and chrome ,but in case of IE blank page coming.I have checked the IE's console for any possible errors but it is also coming blank.

**Comment by RukmaniD** [comment] 2016-02-29 09:06
This JavaScript environment does not support __proto__. This means that react-proxy is unable to proxy React components. Features that rely on react-proxy, such as react-transform-hmr, will not function as expected. 
SCRIPT5009: 'Promise' is undefined 
bundle.js, line 33637 character 88


These 2 errors coming in IE .This application is also not rendering in safari.

**Comment by mxstbr** [comment] 2016-02-29 10:26
Any ideas how to fix that?

**Comment by oliverturner** [comment] 2016-02-29 11:01
You'll need to use the `babel-preset-es2015-loose`

**Comment by oliverturner** [comment] 2016-02-29 11:03
see https://babeljs.algolia.com/docs/advanced/caveats/#internet-explorer 
and https://babeljs.algolia.com/docs/advanced/loose/
for details

**Comment by mxstbr** [comment] 2016-02-29 11:18
Ah thanks @oliverturner!

Do we use anything that loose mode interferes with?

**Comment by oliverturner** [comment] 2016-02-29 11:41
I won't be able to take a look today, sorry :disappointed:

**Comment by RukmaniD** [comment] 2016-02-29 11:42
react-proxy is a dependency for react-transform-hmr ,and react-proxy uses _proto_ which is not suppoted in IE10 .so well have to use loose mode .but it is not clear fromthe documentation how to use this mode.

**Comment by mxstbr** [comment] 2016-02-29 11:47
Replace `babel-preset-es2015` in the `babel` config in the `package.json` with `babel-preset-es2015-loose` *should* fix it. The problem is that loose mode has [a "few" caveats](https://babeljs.algolia.com/docs/advanced/loose/) and we need to make sure we won't run into problems because of that.

**Comment by RukmaniD** [comment] 2016-02-29 12:48
not it wasn't of any help .i have checked with other forums also no reoslution ofr this _proto issue.............. is there a way i can remove hot reloading for ie10 or for all browsers.

**Comment by webdesserts** [comment] 2016-03-21 03:53
@mxstbr since hmr is development only and most likely devs will not be developing continuously in IE10 but rather peeking at it every-so-often. It might be ok to make hmr optional and provide a warning in the docs?

**Comment by mxstbr** [comment] 2016-03-21 04:14
We should remove react transform, see #220. That might fix the issue, and if not, we might be able to provide an opt-out env variable so IE10 users can still develop. Does that sound reasonable?

**Comment by webdesserts** [comment] 2016-03-21 04:21
@mxstbr I was just reading up on that issue actually. Interesting read by @gaearon. Covers many of the problems we ran into while trying to use React-Transform. I agree that would probably solve the issue right now. Might still be good to make hmr optional anyway? Removing React-Transform would definitely push it down the todo list though.

**Comment by mxstbr** [comment] 2016-03-21 04:23
I think it'd be a bit awkward to make hmr opt-out and then remove it soon after, I'd rather just remove it and fix the issue that way. :+1:

**Comment by webdesserts** [comment] 2016-03-21 04:24
@mxstbr would you be removing hmr entirely or just react-transform?

**Comment by mxstbr** [comment] 2016-03-21 04:32
Just react-transform, and replace it with the better approach detailed by Dan in that issue!

**Comment by mxstbr** [comment] 2016-04-06 10:10
Closed in favor of #220!

**Closed by mxstbr** 2016-04-06 10:10 UTC
Labels: unconfirmed-bug
