### ISSUE TITLE
Cancel watcher saga test always passes

### ISSUE THREAD

**Issue by jeremyadavis** [mxstbr/react-boilerplate#1350] opened 2016-12-15 16:23 UTC
The [current test](https://github.com/mxstbr/react-boilerplate/blob/master/app/containers/HomePage/tests/sagas.test.js#L77) for canceling the watcher saga on location change always passes
``` javascript
it('should finally cancel() the forked getReposWatcher saga',
     function* githubDataSagaCancellable() {
      // reuse open fork for more integrated approach
       forkDescriptor = githubDataSaga.next(put(LOCATION_CHANGE));
       expect(forkDescriptor.value).toEqual(cancel(forkDescriptor));
     }
   );
```
 and

``` javascript
it('should finally cancel() the forked getReposWatcher saga',
     function* githubDataSagaCancellable() {
      // reuse open fork for more integrated approach
       forkDescriptor = githubDataSaga.next(put(LOCATION_CHANGE));
       expect(forkDescriptor.value).toNotEqual(cancel(forkDescriptor));
     }
   );
```
both pass.

The test is gone with the latest [conversion to Jest](https://github.com/mxstbr/react-boilerplate/blob/3.4/app/containers/HomePage/tests/sagas.test.js).

Unfortunately I don't have any recommendations on how to properly test that effect so I'm hoping others might have a solution.

**Comment by mxstbr** [comment] 2016-12-16 15:22
Duplicate of #1235

**Closed by mxstbr** 2016-12-16 15:22 UTC
Labels: bug
