### ISSUE TITLE
Homepage tests: Cannot resolve 'file' or 'directory' 

### ISSUE THREAD

**Issue by jbinto** [mxstbr/react-boilerplate#142] opened 2016-02-02 05:58 UTC
https://travis-ci.org/mxstbr/react-boilerplate/builds/106399977#L2106

```
ERROR in ./app/containers/HomePage/tests/actions.test.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../actions in /home/travis/build/mxstbr/react-boilerplate/app/containers/HomePage/tests
 @ ./app/containers/HomePage/tests/actions.test.js 12:15-36
ERROR in ./app/containers/HomePage/tests/actions.test.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../constants in /home/travis/build/mxstbr/react-boilerplate/app/containers/HomePage/tests
 @ ./app/containers/HomePage/tests/actions.test.js 16:17-40
ERROR in ./app/containers/HomePage/tests/reducer.test.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../constants in /home/travis/build/mxstbr/react-boilerplate/app/containers/HomePage/tests
 @ ./app/containers/HomePage/tests/reducer.test.js 12:17-40
ERROR in ./app/containers/HomePage/tests/reducer.test.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../reducer in /home/travis/build/mxstbr/react-boilerplate/app/containers/HomePage/tests
```

**Comment by jbinto** [comment] 2016-02-02 06:00
Not sure what this is about.

**Comment by jbinto** [comment] 2016-02-02 06:03
See https://github.com/webpack/webpack/issues/981

**Comment by mxstbr** [comment] 2016-02-02 09:02
Looking into this now, thanks for notifying me!

**Comment by mxstbr** [comment] 2016-02-02 09:06
This is happening because HomePage no longer has actions or a reducer, so they can't be tested – should be fixed with 1b7c8d5, waiting for Travis at the moment.

**Comment by mxstbr** [comment] 2016-02-02 09:13
God dammit, now travis is erroring because of the following:

```
13.92s$ sudo apt-get update
Get:1 http://us-central1.gce.archive.ubuntu.com precise Release.gpg [198 B]
Get:2 http://us-central1.gce.archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:3 http://us-central1.gce.archive.ubuntu.com precise-backports Release.gpg [198 B]
Get:4 http://us-central1.gce.archive.ubuntu.com precise Release [49.6 kB]
Get:5 http://us-central1.gce.archive.ubuntu.com precise-updates Release [196 kB]
Get:6 http://us-central1.gce.archive.ubuntu.com precise-backports Release [54.3 kB]
Get:7 http://us-central1.gce.archive.ubuntu.com precise/main Sources [934 kB]
Get:8 http://us-central1.gce.archive.ubuntu.com precise/universe Sources [5,019 kB]
Get:9 http://apt.postgresql.org precise-pgdg Release.gpg [819 B]
Hit http://downloads-distro.mongodb.org dist Release.gpg
Get:10 http://apt.postgresql.org precise-pgdg Release [36.5 kB]
Hit http://downloads-distro.mongodb.org dist Release
Get:11 http://apt.postgresql.org precise-pgdg/main amd64 Packages [62.2 kB]
Get:12 http://apt.postgresql.org precise-pgdg/main i386 Packages [62.2 kB]
Ign http://apt.postgresql.org precise-pgdg/main TranslationIndex
Hit http://downloads-distro.mongodb.org dist/10gen amd64 Packages
Get:13 http://security.ubuntu.com precise-security Release.gpg [198 B]
Hit http://ppa.launchpad.net precise Release.gpg
Get:14 http://us-central1.gce.archive.ubuntu.com precise/multiverse Sources [155 kB]
Get:15 http://us-central1.gce.archive.ubuntu.com precise/main amd64 Packages [1,273 kB]
Get:16 http://us-central1.gce.archive.ubuntu.com precise/universe amd64 Packages [4,786 kB]
Hit http://downloads-distro.mongodb.org dist/10gen i386 Packages
Hit http://ppa.launchpad.net precise Release.gpg
Get:17 http://security.ubuntu.com precise-security Release [54.3 kB]
Ign http://downloads-distro.mongodb.org dist/10gen TranslationIndex
Get:18 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:19 http://us-central1.gce.archive.ubuntu.com precise/multiverse amd64 Packages [119 kB]
Get:20 http://us-central1.gce.archive.ubuntu.com precise/main i386 Packages [1,274 kB]
Ign http://apt.postgresql.org precise-pgdg/main Translation-en_US
Get:21 http://us-central1.gce.archive.ubuntu.com precise/universe i386 Packages [4,796 kB]
Get:22 http://ppa.launchpad.net precise Release.gpg [316 B]
Ign http://apt.postgresql.org precise-pgdg/main Translation-en
Hit http://ppa.launchpad.net precise Release.gpg
Get:23 http://us-central1.gce.archive.ubuntu.com precise/multiverse i386 Packages [121 kB]
Get:24 http://us-central1.gce.archive.ubuntu.com precise/main TranslationIndex [3,706 B]
Get:25 http://us-central1.gce.archive.ubuntu.com precise/multiverse TranslationIndex [2,676 B]
Get:26 http://us-central1.gce.archive.ubuntu.com precise/universe TranslationIndex [2,922 B]
Get:27 http://us-central1.gce.archive.ubuntu.com precise-updates/main Sources [495 kB]
Get:28 http://us-central1.gce.archive.ubuntu.com precise-updates/universe Sources [124 kB]
Get:29 http://us-central1.gce.archive.ubuntu.com precise-updates/multiverse Sources [9,759 B]
Get:30 http://us-central1.gce.archive.ubuntu.com precise-updates/main amd64 Packages [973 kB]
Get:31 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:32 http://us-central1.gce.archive.ubuntu.com precise-updates/universe amd64 Packages [272 kB]
Get:33 http://security.ubuntu.com precise-security/main Sources [138 kB]
Get:34 http://us-central1.gce.archive.ubuntu.com precise-updates/multiverse amd64 Packages [16.6 kB]
Get:35 http://us-central1.gce.archive.ubuntu.com precise-updates/main i386 Packages [1,034 kB]
Get:36 http://us-central1.gce.archive.ubuntu.com precise-updates/universe i386 Packages [281 kB]
Get:37 http://us-central1.gce.archive.ubuntu.com precise-updates/multiverse i386 Packages [16.7 kB]
Get:38 http://us-central1.gce.archive.ubuntu.com precise-updates/main TranslationIndex [10.6 kB]
Get:39 http://us-central1.gce.archive.ubuntu.com precise-updates/multiverse TranslationIndex [7,613 B]
Hit http://ppa.launchpad.net precise Release
Get:40 http://us-central1.gce.archive.ubuntu.com precise-updates/universe TranslationIndex [8,333 B]
Get:41 http://us-central1.gce.archive.ubuntu.com precise-backports/main Sources [5,922 B]
Get:42 http://us-central1.gce.archive.ubuntu.com precise-backports/restricted Sources [28 B]
Get:43 http://us-central1.gce.archive.ubuntu.com precise-backports/universe Sources [43.5 kB]
Get:44 http://us-central1.gce.archive.ubuntu.com precise-backports/multiverse Sources [5,750 B]
Get:45 http://us-central1.gce.archive.ubuntu.com precise-backports/main amd64 Packages [6,477 B]
Get:46 http://us-central1.gce.archive.ubuntu.com precise-backports/restricted amd64 Packages [28 B]
Get:47 http://us-central1.gce.archive.ubuntu.com precise-backports/universe amd64 Packages [45.4 kB]
Get:48 http://us-central1.gce.archive.ubuntu.com precise-backports/multiverse amd64 Packages [5,419 B]
Get:49 http://us-central1.gce.archive.ubuntu.com precise-backports/main i386 Packages [6,478 B]
Get:50 http://us-central1.gce.archive.ubuntu.com precise-backports/restricted i386 Packages [28 B]
Get:51 http://us-central1.gce.archive.ubuntu.com precise-backports/universe i386 Packages [45.1 kB]
Get:52 http://us-central1.gce.archive.ubuntu.com precise-backports/multiverse i386 Packages [5,413 B]
Ign http://downloads-distro.mongodb.org dist/10gen Translation-en_US
Get:53 http://us-central1.gce.archive.ubuntu.com precise-backports/main TranslationIndex [202 B]
Get:54 http://us-central1.gce.archive.ubuntu.com precise-backports/multiverse TranslationIndex [202 B]
Get:55 http://us-central1.gce.archive.ubuntu.com precise-backports/restricted TranslationIndex [193 B]
Get:56 http://us-central1.gce.archive.ubuntu.com precise-backports/universe TranslationIndex [205 B]
Get:57 http://us-central1.gce.archive.ubuntu.com precise/main Translation-en [726 kB]
Hit http://ppa.launchpad.net precise Release
Get:58 http://us-central1.gce.archive.ubuntu.com precise/multiverse Translation-en [93.4 kB]
Get:59 http://us-central1.gce.archive.ubuntu.com precise/universe Translation-en [3,341 kB]
Ign http://downloads-distro.mongodb.org dist/10gen Translation-en
Get:60 http://ppa.launchpad.net precise Release [12.9 kB]
Get:61 http://us-central1.gce.archive.ubuntu.com precise-updates/main Translation-en [411 kB]
Get:62 http://us-central1.gce.archive.ubuntu.com precise-updates/multiverse Translation-en [9,603 B]
Get:63 http://us-central1.gce.archive.ubuntu.com precise-updates/universe Translation-en [163 kB]
Get:64 http://us-central1.gce.archive.ubuntu.com precise-backports/main Translation-en [5,737 B]
Get:65 http://us-central1.gce.archive.ubuntu.com precise-backports/multiverse Translation-en [4,838 B]
Get:66 http://ppa.launchpad.net precise Release [12.9 kB]
Get:67 http://us-central1.gce.archive.ubuntu.com precise-backports/restricted Translation-en [14 B]
Get:68 http://us-central1.gce.archive.ubuntu.com precise-backports/universe Translation-en [35.5 kB]
Hit http://ppa.launchpad.net precise Release
Get:69 http://ppa.launchpad.net precise Release [13.0 kB]
Get:70 http://security.ubuntu.com precise-security/universe Sources [45.1 kB]
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Get:71 http://security.ubuntu.com precise-security/multiverse Sources [2,201 B]
Hit http://ppa.launchpad.net precise/main TranslationIndex
Get:72 http://security.ubuntu.com precise-security/main amd64 Packages [583 kB]
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Hit http://ppa.launchpad.net precise/main TranslationIndex
Get:73 http://ppa.launchpad.net precise/main amd64 Packages [682 B]
Get:74 http://ppa.launchpad.net precise/main i386 Packages [685 B]
Get:75 http://ppa.launchpad.net precise/main TranslationIndex [196 B]
Get:76 http://ppa.launchpad.net precise/main amd64 Packages [1,398 B]
Get:77 http://ppa.launchpad.net precise/main i386 Packages [943 B]
Get:78 http://ppa.launchpad.net precise/main TranslationIndex [199 B]
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Hit http://ppa.launchpad.net precise/main TranslationIndex
Get:79 http://ppa.launchpad.net precise/main amd64 Packages [3,359 B]
Get:80 http://ppa.launchpad.net precise/main i386 Packages [3,359 B]
Get:81 http://ppa.launchpad.net precise/main TranslationIndex [199 B]
Hit http://ppa.launchpad.net precise/main Translation-en
Hit http://ppa.launchpad.net precise/main Translation-en
Get:82 http://ppa.launchpad.net precise/main Translation-en [464 B]
Get:83 http://ppa.launchpad.net precise/main Translation-en [735 B]
Hit http://ppa.launchpad.net precise/main Translation-en
Get:84 http://ppa.launchpad.net precise/main Translation-en [1,556 B]
Get:85 http://security.ubuntu.com precise-security/universe amd64 Packages [128 kB]
Get:86 http://security.ubuntu.com precise-security/multiverse amd64 Packages [2,699 B]
Get:87 http://security.ubuntu.com precise-security/main i386 Packages [642 kB]
Get:88 http://security.ubuntu.com precise-security/universe i386 Packages [136 kB]
Get:89 http://security.ubuntu.com precise-security/multiverse i386 Packages [2,875 B]
Get:90 http://security.ubuntu.com precise-security/main TranslationIndex [208 B]
Get:91 http://security.ubuntu.com precise-security/multiverse TranslationIndex [199 B]
Get:92 http://security.ubuntu.com precise-security/universe TranslationIndex [205 B]
Get:93 http://security.ubuntu.com precise-security/main Translation-en [248 kB]
Get:94 http://security.ubuntu.com precise-security/multiverse Translation-en [1,408 B]
Get:95 http://security.ubuntu.com precise-security/universe Translation-en [82.0 kB]
Fetched 29.3 MB in 11s (2,548 kB/s)
Reading package lists... Done
270.77s$ sudo apt-get install -y libappindicator1 fonts-liberation
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  indicator-application libappindicator3-1 libdbusmenu-glib4
  libdbusmenu-gtk3-4 libdbusmenu-gtk4 libindicator3-7 libindicator7
The following NEW packages will be installed:
  fonts-liberation indicator-application libappindicator1 libappindicator3-1
  libdbusmenu-glib4 libdbusmenu-gtk3-4 libdbusmenu-gtk4 libindicator3-7
  libindicator7
0 upgraded, 9 newly installed, 0 to remove and 91 not upgraded.
Need to get 1,551 kB of archives.
After this operation, 3,354 kB of additional disk space will be used.
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise-updates/main libdbusmenu-gtk3-4 amd64 0.6.2-0ubuntu0.2
  503  Service Unavailable [IP: 104.197.12.55 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise/main libindicator3-7 amd64 0.5.0-0ubuntu1
  503  Service Unavailable [IP: 104.197.12.55 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise-updates/main libappindicator1 amd64 0.4.92-0ubuntu1.1
  503  Service Unavailable [IP: 104.197.12.55 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise-updates/main fonts-liberation all 1.07.0-2ubuntu0.1
  503  Service Unavailable [IP: 173.255.118.228 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise/main libindicator7 amd64 0.5.0-0ubuntu1
  503  Service Unavailable [IP: 104.197.12.55 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise-updates/main libdbusmenu-glib4 amd64 0.6.2-0ubuntu0.2
  Connection failed [IP: 173.255.118.228 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise-updates/main libdbusmenu-gtk4 amd64 0.6.2-0ubuntu0.2
  503  Service Unavailable [IP: 173.255.118.228 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise-updates/main libappindicator3-1 amd64 0.4.92-0ubuntu1.1
  503  Service Unavailable [IP: 173.255.118.228 80]
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise/main indicator-application amd64 0.5.0-0ubuntu1
  503  Service Unavailable [IP: 104.197.12.55 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libd/libdbusmenu/libdbusmenu-glib4_0.6.2-0ubuntu0.2_amd64.deb  Connection failed [IP: 173.255.118.228 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libd/libdbusmenu/libdbusmenu-gtk3-4_0.6.2-0ubuntu0.2_amd64.deb  503  Service Unavailable [IP: 104.197.12.55 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libd/libdbusmenu/libdbusmenu-gtk4_0.6.2-0ubuntu0.2_amd64.deb  503  Service Unavailable [IP: 173.255.118.228 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/f/fonts-liberation/fonts-liberation_1.07.0-2ubuntu0.1_all.deb  503  Service Unavailable [IP: 173.255.118.228 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libi/libindicator/libindicator3-7_0.5.0-0ubuntu1_amd64.deb  503  Service Unavailable [IP: 104.197.12.55 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-0ubuntu1.1_amd64.deb  503  Service Unavailable [IP: 173.255.118.228 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/i/indicator-application/indicator-application_0.5.0-0ubuntu1_amd64.deb  503  Service Unavailable [IP: 104.197.12.55 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libi/libindicator/libindicator7_0.5.0-0ubuntu1_amd64.deb  503  Service Unavailable [IP: 104.197.12.55 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/liba/libappindicator/libappindicator1_0.4.92-0ubuntu1.1_amd64.deb  503  Service Unavailable [IP: 104.197.12.55 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command "sudo apt-get install -y libappindicator1 fonts-liberation" failed and exited with 100 during .
```

No idea why it's doing the apt-get, so I think this is a problem with Travis and not ours. Will close this for now, since I believe this is fixed!

**Closed by mxstbr** 2016-02-02 09:13 UTC
Labels: bug

**Comment by mxstbr** [comment] 2016-02-02 09:35
@travisstatus on Twitter confirmed the problem is on their end!
