### ISSUE TITLE
Order of styles vs sanitize is different between dev and prod

### ISSUE THREAD

**Issue by roderik** [mxstbr/react-boilerplate#1102] opened 2016-10-13 13:24 UTC
## Issue Type
- [x] Bug (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/mxstbr/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)
## Description

Using npm start:
<img width="656" alt="screen shot 2016-10-13 at 15 20 55" src="https://cloud.githubusercontent.com/assets/16780/19350589/af000272-9158-11e6-9563-8c06b0c0166e.png">
- font
- normalize
- my css

Using npm run build:

<img width="736" alt="screen shot 2016-10-13 at 15 21 40" src="https://cloud.githubusercontent.com/assets/16780/19350622/cdcd633e-9158-11e6-8f5b-b3001e3ba5c9.png">
- font
- my css
- normalize

Stuff like margins etc gets reset this way in prod.
## Steps to reproduce

Not sure, redid my entire app on the latest version, but not sure why this happens.
# Versions
- Node/NPM: 6.7
- Browser: Chrome / Safari

**Comment by GGAlanSmithee** [comment] 2016-10-13 13:26
Might be related to this https://github.com/webpack/webpack/issues/215 ?

**Comment by roderik** [comment] 2016-10-14 06:56
Could not find an indication of what I could do to fix it. Tried adding some web pack plugins they mention to the dev config to see if they would then return the same result, but no luck. Quick fix, I just commented it out in app.js and my styling is simple enough that it did not matter for now.

I did however noticed something strange. The index.html generated contains the hardcoded link to the main css file. This file does not contain sanitize.css. There is no line for sanitize.css itself in the html. It gets added by javascript (at the end of the head, so after my main.css). It would seem that webpack does not pick up the import of sanitize.css in app.js as I would assume it would be included in the main css file.

**Comment by mxstbr** [comment] 2016-10-17 11:52
Huh that's way annoying! What about loading `sanitize.css` with the file loader like we do for the `.htaccess` file? That should make it possible to always load it before the other CSS?

**Comment by paothegit** [comment] 2016-10-20 20:46
@roderik [this](https://github.com/mxstbr/react-boilerplate/issues/620) might help?

**Comment by mxstbr** [comment] 2016-11-03 10:55
This should not be a problem anymore with the switch to `styled-components`, so I'll close this for now. If you can still replicate this issue on current `master`, feel free to comment again and I'll take a look!

**Closed by mxstbr** 2016-11-03 10:55 UTC
Labels: bug

**Comment by shan-du** [comment] 2017-01-12 16:40
@roderik I encountered the same issue recently as we are using `v3.2.0` which doesn't have `styled-components` yet.
the cause is the way the CSS were loaded (see `webpack.prod.babel.js` & `webpack.base.babel.js`)
all vendor css are loaded with `css-loader` & `style-loader` which are inserted as `<style>` tags but **AFTER** your own component/container css which are loaded and extracted via `extract-text-webpack-plugin` into a `<link>` tag.

dev build doesn't have this issue as it doesn't use `extract-text-webpack-plugin`.

as per @mxstbr on https://github.com/mxstbr/react-boilerplate/issues/1102#issuecomment-258112657, `v3.3.0+` no longer has this issue, but if you are using pre `v3.2.0`, then there's no way around that I know of, so my next best solution is to use `extract-text-webpack-plugin` for the vendor css as well, this way all your CSS (custom & vendor) are compacted into 1 file, but the order is correct.
I changed my `webpack.base.babel.js`:
```
...
    {
      // Transform our own .css files with PostCSS and CSS-modules
      test: /\.css$/,
      exclude: /node_modules/,
      loader: options.cssLoaders,
    },
    {
      test: /\.css$/,
      include: /node_modules/,
      loader: options.vendorCssLoaders,
    },
...
```
and added this to `webpack.prod.babel.js`
```
  vendorCssLoaders: ExtractTextPlugin.extract({
    fallbackLoader: 'style-loader',
    loader: 'css-loader',
  }),
```
