### ISSUE TITLE
Question re: project scripts / commands

### ISSUE THREAD

**Issue by datapimp** [mxstbr/react-boilerplate#471] opened 2016-06-05 10:13 UTC
Are there plans or is work currently underway to introduce a proper CLI library to the project? e.g. commander

**Comment by mxstbr** [comment] 2016-06-05 17:24
Yes and no.

I'd love to create a Rails-style scaffolding CLI for the React ecosystem and planned to make it happen soon–ish, but didn't have the time to make it happen so far. (https://github.com/mxstbr/react-boilerplate-cli) Would you want to lead the effort?

The main reasoning behind that would be that you could do `react-boilerplate init` (or whatever the command is…) and it'll let you choose which techniques you'd like to include. (i.e. I don't want ImmutableJS but I do want reselect,…)

*Pinging other people that expressed interest in making this happen: @oliverturner @vesln et al*

**Comment by datapimp** [comment] 2016-06-06 04:38
Personally I really like the `react-native-cli` behavior -- one global install that you don't usually mess around with again, and then that is responsible for finding the closest `react-native` library based on the CWD and loading in any framework commands or project specific commands it finds.

I think that would work very well in this project and would be an improvement over the npm run scripts.  

Happy to own that just didn't want to start if it was already being handled.  I prefer commander but am open to suggestions in case there are better CLI frameworks

**Comment by mxstbr** [comment] 2016-06-06 08:37
Commander sounds excellent! Can't wait to see what you come up with!

**Comment by mxstbr** [comment] 2016-07-19 07:52
Closing this as a duplicate of #180, let's continue discussing there!

**Closed by mxstbr** 2016-07-19 07:52 UTC
Labels: question
