### ISSUE TITLE
Chunk caching and using hashes in their names

### ISSUE THREAD

**Issue by fireantik** [mxstbr/react-boilerplate#134] opened 2016-01-30 09:25 UTC
Webpack makes it really easy to use hashes in chunk names, which makes these chunks permanently cacheable. [Google has a nice article on this topic.](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching) This will achieve [Progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement) for browsers that support caching headers but not Application Cache and ServiceWorker, it will also allow caching of actual content pages like readme.

What I propose:

- Creating folder for permanently cached content, for example 'static'.
- Adding `[hash]` to `filename` and `chunkFilename`.
- Moving all content that has a hash in its filename into static folder.
- Adding `Cache-Control:public, max-age=31536000` header (and/or similar permanent cache headers) for static folder into common server configurations like `.htaccess`.

**Comment by mxstbr** [comment] 2016-01-30 09:28
Duplicate of #127 as far as I can tell.

@okonet is working on this – thanks for reminding me!

**Closed by mxstbr** 2016-01-30 09:28 UTC
Labels: enhancement

**Comment by fireantik** [comment] 2016-01-30 09:32
Ah, my apologies. I should read existing issues better next time!
